---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyquant)
library(tidyverse)
library(timetk)
library(tibbletime)
```

Idea, take SP500, sample randomly, find highest lowest skew. 
Or, take all of SP500, take top 5, bottom 5. 
Group by sector, high low skew per sector.

App idea, choose a portfolio, see how distributed across the globe, run diagnostics, run montecarlo

```{r}
symbols <- c( "TAP", "VLO", "AFL", "ESRX", 
             "ABC", "QCOM", "SWKS", "LRCX",
             "HST", "HCN", "NFLX")



tq_prices <- symbols %>%
  tq_get(get = "stock.prices", from = "1990-01-01") %>% 
  group_by(symbol) %>% 
  filter(row_number() ==1) 

quandl_api_key("d9EidiiDWoFESfdk5nPy")

wage_growth <- "FRED/CES0500000003" %>%
    tq_get(get      = "quandl",
           collapse = "monthly",
           transform    = "rdiff",
           from = "1990-01-01")


wage_growth <- "FRED/A576RC1" %>%
    tq_get(get      = "quandl",
           collapse = "monthly",
           transform    = "rdiff",
           from = "1989-12-01")

asset_returns_dplyr_byhand <- 
  prices %>% 
  to.monthly(indexAt = "last", OHLC = FALSE) %>% 
  tk_tbl(preserve_index = TRUE, rename_index = "date")%>%
  gather(asset, returns, -date) %>% 
  group_by(asset) %>%  
  mutate(returns = (log(returns) - log(lag(returns)))) %>%
  spread(asset, returns) %>% 
  select(date, symbols) %>% 
  slice(-1)
# get from 2000 or as early as possible, then filter based on user input - put it into a database, then filter it. then do the calcs
input_sector <- "Financials"
sp500_sector_prices <- 
  tq_index("SP500") %>%
  filter(sector == input_sector) %>%
  #sample_n(200) %>% 
  tq_get(get = "stock.prices", from = "2016-01-01") 

sp500_random_20_returns <- 
  sp500_sector_prices %>% 
  #group_by(sector, symbol) %>% 
  select(date, symbol, sector, adjusted) %>% 
  #mutate to monthly returns; then could stay in dplyr
  #tq_transmute(adjusted, periodReturn, period = "monthly", col_rename = "returns")
  #tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
  #gather(asset, returns, -date) %>% 
  group_by(symbol) %>%  
  mutate(returns = (log(adjusted) - log(lag(adjusted)))) %>%
  na.omit() %>% 
  mutate(skew = skewness(returns),
            skew_byhand = 
              (sum((returns - mean(returns))^3)/length(returns))/
              ((sum((returns - mean(returns))^2)/length(returns)))^(3/2),
            kurt = kurtosis(returns),
            kurt_byhand = 
              ((sum((returns - mean(returns))^4)/length(returns))/
              ((sum((returns - mean(returns))^2)/length(returns))^2)) - 3, 
         stddevi = sd(returns)) %>% 
  #ungroup() %>%
  group_by(sector) %>% 
  filter(stddevi == min(stddevi) | stddevi == max(stddevi)) 

sp500_random_20_returns %>%
  ggplot(aes(x = returns, fill = symbol, color = symbol)) +
  geom_histogram(binwdidth = .005) + 
  geom_density(color = "blue") +
  facet_wrap(~symbol)


```

```{r}

  plot <- sp500_random_100_returns %>%
  filter(symbol %in% sp500_random_100_skew$symbol) %>%
  mutate(skew = skewness(returns),
         min_max = ifelse(skew < 0, "min", "max")) %>% 
  group_by(symbol) %>%
 # filter(sector == "Materials") %>% 
  ggplot(aes(x = returns, color = symbol)) +
  stat_density(geom = "line", size = .75) +
  facet_grid(min_max ~ sector) +
    theme(axis.text.x = element_text(angle = 90))
  
  plot
```

```{r}


test <- 
  sp500_skew_sectorized %>%
  ungroup() %>% 
  filter(skew == min(skew) | skew == max(skew))
  
```


```{r, warning=FALSE, message=FALSE}
symbols <- c("SPY","EFA", "IJS", "EEM","AGG")
```

XTS World

```{r}
prices <- 
  getSymbols(symbols, src = 'yaho0', from = "2013-01-01", 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Cl(get(.))) %>%
  reduce(merge) %>% 
  `colnames<-`(symbols)

prices_monthly <- to.monthly(prices, indexAt = "first", OHLC = FALSE)

asset_returns_xts <- na.omit(Return.calculate(prices_monthly, method = "log"))

w <- c(0.25, 0.25, 0.20, 0.20, 0.10)

portfolio_returns_xts_rebalanced_monthly <- 
  Return.portfolio(asset_returns_xts, weights = w, rebalance_on = "months") %>%
  `colnames<-`("returns") %>% 
  skewness(returns)
```

Tidyverse

```{r}
asset_returns_tidy <-  
  prices %>% 
  to.monthly(indexAt = "last", OHLC = FALSE) %>% 
  tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
  gather(asset, returns, -date) %>% 
  group_by(asset) %>%  
  mutate(returns = (log(returns) - log(lag(returns))))
```

Tidyquant

```{r}
asset_returns <- 
  symbols %>% 
  tq_get(get = "stock.prices", from = "1990-01-01") %>% 
  group_by(symbol) %>% 
  tq_transmute(adjusted, periodReturn, period = "weekly", col_rename = "returns")
```

And a Tidyquant method for testing out variations of our portfolio

```{r message=FALSE, warning=FALSE}

mult_weekly_returns <- tq_repeat_df(asset_returns, n = 3)

weights <-  c(0.25, 0.25, 0.20, 0.20, 0.10,
              0.20, 0.20, 0.25, 0.25, 0.10,
              0.20, 0.20, 0.20, 0.20, 0.20)


weights_table <- tibble(symbols) %>%
    tq_repeat_df(n = 3) %>%
    bind_cols(tibble(weights)) %>%
    group_by(portfolio)

levels <- c("date", paste("portfolio_", 1:3, sep = ""))

portfolios_3 <- 
  mult_weekly_returns %>%
  tq_portfolio(assets_col = symbol,
               returns_col = returns,
               weights = weights_table,
               col_rename = NULL,
               wealth.index = FALSE) %>% 
  spread(portfolio, portfolio.returns) %>% 
  `colnames<-`(levels)

skews <- 
  portfolios_3 %>%
  select(-date) %>%
  gather(portfolio, returns) %>%
  group_by(portfolio) %>%
  na.omit() %>% 
  summarise(skew = skewness(returns),
            skew_byhand = 
              (sum((returns - mean(returns))^3)/length(returns))/
              ((sum((returns - mean(returns))^2)/length(returns)))^(3/2),
            kurt = kurtosis(returns),
            kurt_byhand = 
              ((sum((returns - mean(returns))^4)/length(returns))/
              ((sum((returns - mean(returns))^2)/length(returns))^2)) - 3)

```

```{r}
portfolio_returns_risk_levels %>%
  select(date, risk_level_10) %>% 
  gather(risk, return, -date) %>% 
  ggplot(aes(x = date, y = return, color = risk)) +
  geom_point() +
  facet_wrap(~risk)
```


```{r}
portfolio_returns_risk_levels %>%
  select(date, risk_level_7) %>%
  gather(risk, return, -date) %>% 
  ggplot(aes(x = return, color = risk)) +
  geom_density()
```
 
```{r}
portfolio_returns_risk_levels %>%
  select(date, risk_level_2, risk_level_10) %>%
  gather(risk, return, -date) %>% 
  ggplot(aes(x = return, color = risk)) +
  geom_histogram(alpha = 0.25, binwidth = .01, fill = "cornflowerblue") +
  facet_wrap(~risk)

```


```{r}
index_monthly_returns <- symbols %>% 
  tq_get(get = "stock.prices", from = "1990-01-01") %>% 
  group_by(symbol) %>% 
  tq_transmute(adjusted, periodReturn, period = "monthly", col_rename = "returns")


mult_monthly_returns <- tq_repeat_df(index_monthly_returns, n = 10)


monthly_returns_risk_levels <- 
  mult_monthly_returns %>%
  tq_portfolio(assets_col = symbol,
               returns_col = returns,
               weights = weights_table,
               col_rename = NULL,
               wealth.index = FALSE) %>% 
  spread(portfolio, portfolio.returns) %>% 
  `colnames<-`(levels)
```

```{r}
monthly_returns_risk_levels %>%
  select(date, risk_level_9, risk_level_10) %>% 
  gather(risk, return, -date) %>% 
  ggplot(aes(x = date, y = return, color = risk)) +
  geom_point() +
  facet_wrap(~risk)
```

```{r}
monthly_returns_risk_levels %>%
  select(date, risk_level_9, risk_level_10) %>%
  gather(risk, return, -date) %>% 
  ggplot(aes(x = return, color = risk)) +
  geom_density() +
  facet_wrap(~risk)
```

```{r}
monthly_returns_risk_levels %>%
  select(date, risk_level_9, risk_level_10) %>%
  gather(risk, return, -date) %>% 
  ggplot(aes(x = return, color = risk)) +
  geom_histogram(alpha = 0.25, binwidth = .01, fill = "white") +
  facet_wrap(~risk)

```





```{r}


    # compute the observed moments of x around the mean
    x <- monthly_returns_risk_levels$risk_level_5
    n <- length(x) 
    mean <- mean(x)
    first_moment <- sum((x - mean)^1)/n
    
    second_moment <- sum((x - mean)^2)/n
    third_moment <- sum((x - mean)^3)/n
    fourth_moment <- sum((x - mean)^4)/n

    skew <- third_moment/(second_moment)^(3/2)
    
    kurt <- (fourth_moment/(second_moment^2)) - 3
    
roll_k <- rollapply(x, 30,  kurtosis)

skewness(x)
kurtosis(x)

data <- sqrt(rnorm(1000))
```


